
class window.Sprite extends Modular
	image: (url, onload=->) ->
		@img = new Image()
		@img.src = url
		@img.onload = onload
		@
	draw: (ctx) ->
		ctx.drawImage @img, 0, 0, @w, @h
	@is Drawable

class window.TileLayer extends Sprite
	init: -> @tileSize 100
	version: -> 2
	tileSize: (@tileWidth, @tileHeight=@tileWidth) -> @
	drawTile: (ctx, x, y) ->
		x *= @tileWidth
		y *= @tileHeight
		ctx.drawImage @img,x,y,@tileWidth,@tileHeight
	draw: (ctx, game) ->
		{width, height} = game.canvas.first()
		for x in [0...width / @tileWidth] by 1
			for y in [0...height / @tileHeight] by 1
				@drawTile ctx, x, y
	@is Drawable

window.Textures = [
	"bRoof1.jpg",
	"bStonWll1.jpg",
	"bStonWll1S.jpg",
	"bStonWll1SW2.jpg",
	"bStonWll1SY.jpg",
	"bStonWll1SYfr1.jpg",
	"bStonWll1Sdw.jpg",
	"bStonWll1Sfr1.jpg",
	"bStonWll1Spllr.jpg",
	"bStonWll1Swmp.jpg",
	"bStonWll1SwmpY.jpg",
	"bStonWll1W1.jpg",
	"bStonWll1W2.jpg",
	"bStonWll1archL.jpg",
	"bStonWll1archL2.jpg",
	"bStonWll1archR.jpg",
	"bStonWll1archR2.jpg",
	"bStonWll1dw.jpg",
	"bStonWll1fr1.jpg",
	"bStonWll1pllr.jpg",
	"bStonWll1pllrW1.jpg",
	"bStonWll1pllrW2.jpg",
	"bStonWll2.jpg",
	"bStonWll3.jpg",
	"bStonWll3road.jpg",
	"bStonWll3t.jpg",
	"bStonWll3tCw.jpg",
	"bStonWll5.jpg",
	"bStonWll5S.jpg",
	"bStonWll5ST.jpg",
	"bStonWll5SW2.jpg",
	"bStonWll5T.jpg",
	"bStonWll5TW2.jpg",
	"bStonWll5W2.jpg",
	"brick-cinder1-0.jpg",
	"brick-cinder1-0_str_clean.jpg",
	"brick-cinder1-0_str_drty.jpg",
	"brick-cinder1-1.jpg",
	"brick-cinder1-1_str_clean.jpg",
	"brick-cinder1-1_str_drty.jpg",
	"brick-cinder2-0.jpg",
	"brick-crete1-0.jpg",
	"brick-darkred1-0.jpg",
	"brick-dirty1-0.jpg",
	"brick-dirty1-0_poster1.jpg",
	"brick-indoor1-0.jpg",
	"brick-plain1-titled.jpg",
	"brick-plain1.jpg",
	"brick-rough1-0.jpg",
	"brick-rough1-0_plain.jpg",
	"brick-whitewash1-0.jpg",
	"brick-whitewash1-0_worn1.jpg",
	"brick-whitewash1-0_worn2.jpg",
	"crate-wood1-0_side.jpg",
	"crate-wood1-0_top.jpg",
	"crete-dirty1-0.jpg",
	"crete-dirty1-0_poster.jpg",
	"crete-pave1-0.jpg",
	"crete-pave1-0_clean1.jpg",
	"crete-pave2-0.jpg",
	"crete-pave2-1.jpg",
	"crete-pave2-3.jpg",
	"crete-silo1-0.jpg",
	"crete-silo1-0_bolts.jpg",
	"crete-silo1-0_bolts_gaps.jpg",
	"crete-silo1-0_gaps.jpg",
	"crete-silo2-0.jpg",
	"crete-silo2-0_muck.jpg",
	"crete-wall1-0.jpg",
	"crete-wall2-0.jpg",
	"dirt.jpg",
	"door-wood0-0.jpg",
	"door-wood1-0.jpg",
	"door-wood3-0.jpg",
	"girder1.jpg",
	"grass.jpg",
	"ground-cracked-0.jpg",
	"ground-grass1-0.jpg",
	"ground-grass1-1.jpg",
	"ground-grass1-1_road1.jpg",
	"ground-grass1-1_roadend1.jpg",
	"ground-grass1-2.jpg",
	"ground-grass1-3.jpg",
	"ground-gravel1-0.jpg",
	"ground-gravel1-0_snow.jpg",
	"ground-rock-0.jpg",
	"ground-rock-0_pale.jpg",
	"ground-snow1-0.jpg",
	"ground-snow1-0_footprints.jpg",
	"indoor-wall1-0.jpg",
	"indoor-wall1-0_doorframe.jpg",
	"juracek-brick1-0.jpg",
	"juracek-brick2-0.jpg",
	"juracek-whwll-0.jpg",
	"juracek-whwll-0_wndw.jpg",
	"metal-cage1-0.jpg",
	"metal-mdrn1-0_ceil1.jpg",
	"metal-mdrn1-0_flr1.jpg",
	"metal-mdrn1-0_flr2.jpg",
	"metal-mdrn1-0_flr3.jpg",
	"metal-mdrn1-0_flr4.jpg",
	"metal-mdrn1-0_light.jpg",
	"metal-mdrn1-0_smlight.jpg",
	"metal-mdrn1-0_trim1.jpg",
	"metal-mdrn1-0_trim2.jpg",
	"metal-vent1-0.jpg",
	"metal-vent1-0_clean.jpg",
	"rock-black1-0.jpg",
	"rock-brown1-0.jpg",
	"rock-icey-moss.jpg",
	"rock-icey-mossgrad.jpg",
	"rock-icey.jpg",
	"rock-snow1-both.jpg",
	"rock-snow1.jpg",
	"stone-brown1-0.jpg",
	"stone-rough1-0.jpg",
	"stone-rough1-0_lighter.jpg",
	"stone-rough1-0_snow.jpg",
	"stone-rough1-tan.jpg",
	"stone-rough2-0.jpg",
	"stone-vary1-0.jpg",
	"stone-vary1-0_ground.jpg",
	"stone-vary1-0_iced.jpg",
	"stone-vary1-0_snow1.jpg",
	"stone-vary1-0_snow1b.jpg",
	"stone-vary1-0_snow2.jpg",
	"stone-vary1-1.jpg",
	"stone-vary1-2.jpg",
	"trim-plaster1-0.jpg",
	"wood-horiz1-0.jpg",
	"wood-nasty1-0.jpg",
	"wood-nasty1-0_horiz.jpg",
	"wood-nasty1-0_mucky.jpg",
	"wood-nasty1-0_mucky2.jpg",
	"wood-nasty2-0.jpg",
	"wood-nasty2-0_lt.jpg",
	"wood-nasty2-0_lt_snow.jpg",
	"wood-nasty2-0_snow1.jpg",
]
